import type { Product, Category, Order, Customer, Coupon, RevenueDataPoint, TopProduct } from './types'

// ─── Categories ───────────────────────────────────────────────────────────────

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Smartphones',
    slug: 'smartphones',
    image: '/assets/heroimage1.jpg',
    description: 'Premium mobile devices crafted for the discerning user.',
    productCount: 8,
  },
  {
    id: 'cat-2',
    name: 'Laptops',
    slug: 'laptops',
    image: '/assets/heroimage2.jpg',
    description: 'High-performance computing for professionals.',
    productCount: 6,
  },
  {
    id: 'cat-3',
    name: 'Audio',
    slug: 'audio',
    image: '/assets/heroimage3.png',
    description: 'Immersive sound experiences for audiophiles.',
    productCount: 10,
  },
  {
    id: 'cat-4',
    name: 'Gaming',
    slug: 'gaming',
    image: '/assets/heroimage4.jpg',
    description: 'Elite gear engineered for peak performance.',
    productCount: 7,
  },
]

// ─── Products ─────────────────────────────────────────────────────────────────

export const products: Product[] = [
  {
    id: 'prod-1',
    slug: 'samsung-galaxy-s22',
    name: 'Samsung Galaxy S22',
    brand: 'Samsung',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    images: ['/assets/s22.png', '/assets/heroimage1.jpg'],
    price: 1599,
    compareAtPrice: 1899,
    shortDescription:
      'The Galaxy S22 redefines mobile photography with its expert RAW camera and Dynamic AMOLED display.',
    description:
      'Experience the pinnacle of mobile innovation with the Samsung Galaxy S22. Featuring a stunning 6.1" Dynamic AMOLED 2X display with a 120Hz adaptive refresh rate, the S22 adapts to whatever you are doing for an incredibly smooth experience. The new Expert RAW camera system captures detail in any light, while the Snapdragon 8 Gen 1 processor ensures lightning-fast performance for everything you demand.',
    details: [
      'Display: 6.1" Dynamic AMOLED 2X, 120Hz',
      'Processor: Snapdragon 8 Gen 1',
      'RAM: 8GB | Storage: 256GB',
      'Camera: 50MP Wide + 12MP Ultra-wide + 10MP Telephoto',
      'Battery: 3700mAh with 25W fast charging',
      'OS: Android 12 | One UI 4.1',
      'Colors: Phantom Black, Phantom White, Green, Pink Gold',
    ],
    careInstructions: [
      'IP68 water and dust resistance rating',
      'Use a soft, lint-free cloth for cleaning',
      'Avoid exposing to extreme temperatures',
    ],
    shippingInfo: 'Free express shipping. Delivered within 2–4 business days.',
    box: ['Samsung Galaxy S22', 'USB-C Cable', 'SIM Ejector Tool', 'Quick Start Guide'],
    variants: [
      { id: 'v1', color: 'Phantom Black', colorHex: '#1A1A1A', stock: 15, sku: 'S22-BLK-256', size: '256GB' },
      { id: 'v2', color: 'Phantom White', colorHex: '#F0F0F0', stock: 10, sku: 'S22-WHT-256', size: '256GB' },
      { id: 'v3', color: 'Green', colorHex: '#4A7C59', stock: 5, sku: 'S22-GRN-256', size: '256GB' },
      { id: 'v4', color: 'Pink Gold', colorHex: '#C9956A', stock: 8, sku: 'S22-PNK-256', size: '256GB' },
    ],
    tags: ['smartphone', 'samsung', '5g', 'android'],
    rating: 4.7,
    reviewCount: 284,
    reviews: [
      {
        id: 'r1',
        author: 'Alexandra M.',
        location: 'New York, USA',
        rating: 5,
        title: 'Absolutely stunning device',
        body: 'The camera quality is exceptional — night shots look like they were taken with a professional DSLR. The build quality feels genuinely premium in hand.',
        date: '2024-03-15',
        verified: true,
      },
      {
        id: 'r2',
        author: 'James K.',
        location: 'London, UK',
        rating: 4,
        title: 'Near-perfect flagship',
        body: 'Battery life could be better, but everything else is flawless. Display is the best I have ever seen on a smartphone.',
        date: '2024-02-28',
        verified: true,
      },
      {
        id: 'r3',
        author: 'Sophie L.',
        location: 'Paris, France',
        rating: 5,
        title: 'Worth every penny',
        body: "I upgraded from an S20 and the difference is night and day. The performance is buttery smooth and I love the new camera system.",
        date: '2024-01-10',
        verified: true,
      },
    ],
    stock: 38,
    sku: 'SAM-S22-MAIN',
    weight: 168,
    isNew: true,
    isFeatured: true,
    status: 'active',
    createdAt: '2024-01-01',
  },
  {
    id: 'prod-2',
    slug: 'hp-victus-gaming-laptop',
    name: 'HP Victus Gaming Laptop',
    brand: 'HP',
    category: 'Laptops',
    categorySlug: 'laptops',
    images: ['/assets/victuslaptop.png', '/assets/heroimage2.jpg'],
    price: 1799,
    shortDescription:
      'Dominate every game with the HP Victus — RTX graphics, AMD Ryzen power, and a 144Hz display.',
    description:
      'The HP Victus Gaming Laptop is engineered for serious gamers who demand uncompromised performance. Powered by the AMD Ryzen 7 7745HX processor and NVIDIA GeForce RTX 4060 graphics, it handles the most demanding titles with ease. The 15.6" FHD IPS display with 144Hz refresh rate keeps gameplay fluid and responsive, while dual-channel DDR5 memory ensures multitasking never slows you down.',
    details: [
      'Display: 15.6" FHD IPS, 144Hz',
      'Processor: AMD Ryzen 7 7745HX',
      'GPU: NVIDIA GeForce RTX 4060 8GB',
      'RAM: 16GB DDR5 | Storage: 512GB NVMe SSD',
      'Battery: 70Wh with fast charging',
      'OS: Windows 11 Home',
      'Ports: USB-A × 3, USB-C, HDMI 2.1, RJ-45',
    ],
    shippingInfo: 'Free express shipping. Delivered within 3–5 business days.',
    box: ['HP Victus Laptop', '150W Power Adapter', 'Documentation Pack'],
    variants: [
      { id: 'v1', color: 'Mica Silver', colorHex: '#C0C0C0', stock: 12, sku: 'VICTUS-SLV-512' },
      { id: 'v2', color: 'Performance Blue', colorHex: '#1E3A5F', stock: 7, sku: 'VICTUS-BLU-512' },
    ],
    tags: ['laptop', 'gaming', 'rtx', 'amd', 'hp'],
    rating: 4.5,
    reviewCount: 156,
    reviews: [
      {
        id: 'r1',
        author: 'Marcus T.',
        location: 'Toronto, Canada',
        rating: 5,
        title: 'Incredible gaming performance',
        body: 'Runs AAA titles at ultra settings without breaking a sweat. The 144Hz display is a game-changer — literally.',
        date: '2024-04-02',
        verified: true,
      },
      {
        id: 'r2',
        author: 'Priya S.',
        location: 'Sydney, Australia',
        rating: 4,
        title: 'Great value for the spec sheet',
        body: 'Purchased for content creation and gaming. Handles 4K video editing smoothly. Fan noise under full load is noticeable but acceptable.',
        date: '2024-03-18',
        verified: true,
      },
    ],
    stock: 19,
    sku: 'HP-VICTUS-MAIN',
    weight: 2100,
    isNew: false,
    isFeatured: true,
    status: 'active',
    createdAt: '2024-01-15',
  },
  {
    id: 'prod-3',
    slug: 'dual-tower-speaker-system',
    name: 'Dual Tower Speaker System',
    brand: 'Resonance Audio',
    category: 'Audio',
    categorySlug: 'audio',
    images: ['/assets/doublespeaker.png', '/assets/heroimage3.png'],
    price: 2699,
    compareAtPrice: 3199,
    shortDescription:
      'Fill any room with room-filling, studio-grade sound from these precision-engineered tower speakers.',
    description:
      'The Resonance Dual Tower Speaker System delivers an uncompromising hi-fi experience. With a 3-way driver configuration, dedicated tweeters, mid-range drivers, and a 10" woofer per tower, you experience music exactly as the artist intended. The proprietary cabinet resonance dampening technology eliminates coloration and distortion, leaving only pure, precise audio.',
    details: [
      'Driver configuration: 3-way (tweeter, mid-range, woofer)',
      'Frequency response: 28Hz – 40kHz',
      'Sensitivity: 91dB @ 1W/1m',
      'Impedance: 8 Ohms',
      'Power handling: 200W RMS / 400W Peak',
      'Dimensions: H: 110cm × W: 28cm × D: 32cm (per tower)',
      'Finishes: Satin Black, Walnut Veneer',
    ],
    shippingInfo: 'White-glove delivery included. Setup service available.',
    box: ['2× Tower Speaker', 'Speaker Cables (3m pair)', 'Isolation Feet', 'Manual'],
    variants: [
      { id: 'v1', color: 'Satin Black', colorHex: '#1A1A1A', stock: 6, sku: 'RESON-BLK' },
      { id: 'v2', color: 'Walnut Veneer', colorHex: '#7D5A3C', stock: 4, sku: 'RESON-WAL' },
    ],
    tags: ['speakers', 'hi-fi', 'audio', 'tower', 'stereo'],
    rating: 4.9,
    reviewCount: 87,
    reviews: [
      {
        id: 'r1',
        author: 'Henrik B.',
        location: 'Stockholm, Sweden',
        rating: 5,
        title: 'Concert hall in my living room',
        body: "These speakers are extraordinary. The soundstage is wide and deep, vocals are crystal clear, and the bass is tight and controlled. Worth every cent.",
        date: '2024-02-14',
        verified: true,
      },
      {
        id: 'r2',
        author: 'Claire W.',
        location: 'Melbourne, Australia',
        rating: 5,
        title: 'Audiophile-grade at a fair price',
        body: 'I have owned speakers costing three times as much that do not perform as well. The walnut veneer finish is also gorgeous.',
        date: '2024-01-29',
        verified: true,
      },
    ],
    stock: 10,
    sku: 'RESON-TOWER-MAIN',
    weight: 18000,
    isNew: false,
    isFeatured: false,
    status: 'active',
    createdAt: '2023-11-20',
  },
  {
    id: 'prod-4',
    slug: 'elite-gaming-headset-pro',
    name: 'Elite Gaming Headset Pro',
    brand: 'Apex Audio',
    category: 'Gaming',
    categorySlug: 'gaming',
    images: ['/assets/gamingheadphone.png', '/assets/heroimage4.jpg'],
    price: 1799,
    shortDescription:
      'Positional 7.1 surround, 50mm planar magnetic drivers, and all-day comfort for elite competitive play.',
    description:
      'Built for champions who refuse to compromise, the Elite Gaming Headset Pro combines Apex Audio\'s planar magnetic driver technology with best-in-class 7.1 virtual surround sound. Hear footsteps, bullets, and environmental cues with pinpoint precision. The aircraft-grade aluminum headband and memory foam ear cushions deliver marathon gaming sessions without fatigue.',
    details: [
      'Drivers: 50mm Planar Magnetic',
      'Frequency response: 10Hz – 40kHz',
      'Surround: 7.1 Virtual Surround (USB mode)',
      'Microphone: Detachable uni-directional, noise-cancelling',
      'Connection: USB-A + 3.5mm analog',
      'Cable length: 2m braided',
      'Weight: 320g',
    ],
    careInstructions: [
      'Store in the included carry pouch when not in use',
      'Clean ear cushions with a slightly damp cloth',
      'Avoid bending the headband beyond natural flex range',
    ],
    shippingInfo: 'Free express shipping. Delivered within 2–4 business days.',
    box: ['Elite Gaming Headset', 'Detachable Microphone', 'USB-A Adapter', 'Carry Pouch', '3.5mm Cable'],
    variants: [
      { id: 'v1', color: 'Midnight Black', colorHex: '#111111', stock: 20, sku: 'APEX-BLK' },
      { id: 'v2', color: 'Arctic White', colorHex: '#F0F0F0', stock: 11, sku: 'APEX-WHT' },
      { id: 'v3', color: 'Crimson Red', colorHex: '#C0392B', stock: 3, sku: 'APEX-RED' },
    ],
    tags: ['headset', 'gaming', '7.1 surround', 'planar magnetic'],
    rating: 4.8,
    reviewCount: 203,
    reviews: [
      {
        id: 'r1',
        author: 'DeShawn R.',
        location: 'Atlanta, USA',
        rating: 5,
        title: 'Best gaming headset I have ever owned',
        body: 'The positional audio is insane — I can hear exactly where enemies are in games. Mic quality is also studio-level clear.',
        date: '2024-04-10',
        verified: true,
      },
      {
        id: 'r2',
        author: 'Yuki T.',
        location: 'Tokyo, Japan',
        rating: 5,
        title: 'Premium in every way',
        body: 'The planar magnetic drivers are a revelation compared to standard dynamic drivers. Music listening is exceptional too.',
        date: '2024-03-30',
        verified: true,
      },
      {
        id: 'r3',
        author: 'Fatima A.',
        location: 'Dubai, UAE',
        rating: 4,
        title: 'Almost perfect',
        body: 'Excellent sound and build quality. Docked one star because the USB dongle is quite large. Otherwise flawless.',
        date: '2024-02-05',
        verified: true,
      },
    ],
    stock: 34,
    sku: 'APEX-HEADSET-MAIN',
    weight: 320,
    isNew: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2024-02-01',
  },
  {
    id: 'prod-5',
    slug: 'samsung-galaxy-s22-ultra',
    name: 'Samsung Galaxy S22 Ultra',
    brand: 'Samsung',
    category: 'Smartphones',
    categorySlug: 'smartphones',
    images: ['/assets/s22.png'],
    price: 2199,
    shortDescription: 'The ultimate S22 with built-in S Pen, 200MP camera, and titanium frame.',
    description:
      'The Samsung Galaxy S22 Ultra is the pinnacle of the S22 lineup, integrating the legendary S Pen stylus natively into the device. With a 200MP primary camera, quad-lens rear system, and the industry\'s most powerful mobile processor, the S22 Ultra is the closest thing to a professional camera, productivity powerhouse, and gaming machine — all in one.',
    details: [
      'Display: 6.8" Dynamic AMOLED 2X, 120Hz',
      'Processor: Snapdragon 8 Gen 1',
      'RAM: 12GB | Storage: 512GB',
      'Camera: 200MP + 12MP + 10MP × 2',
      'Battery: 5000mAh with 45W fast charging',
      'S Pen included',
    ],
    shippingInfo: 'Free express shipping. Delivered within 2–4 business days.',
    box: ['Samsung Galaxy S22 Ultra', 'S Pen', 'USB-C Cable', 'Quick Start Guide'],
    tags: ['smartphone', 'samsung', 's-pen', '5g'],
    rating: 4.9,
    reviewCount: 421,
    reviews: [],
    stock: 22,
    sku: 'SAM-S22U-MAIN',
    isNew: false,
    isFeatured: false,
    status: 'active',
    createdAt: '2024-01-05',
  },
  {
    id: 'prod-6',
    slug: 'apex-wireless-earbuds-pro',
    name: 'Apex Wireless Earbuds Pro',
    brand: 'Apex Audio',
    category: 'Audio',
    categorySlug: 'audio',
    images: ['/assets/gamingheadphone.png'],
    price: 449,
    compareAtPrice: 549,
    shortDescription: 'ANC earbuds with 30-hour battery, spatial audio, and an IPX5 rating.',
    description:
      'The Apex Wireless Earbuds Pro redefine true wireless audio. Active noise cancellation powered by four microphones eliminates the outside world, while spatial audio creates a three-dimensional soundscape around you. A 30-hour total battery life (7h earbuds + 23h case) means they last through any journey.',
    details: [
      'Driver: 11mm custom dynamic',
      'ANC: Adaptive Active Noise Cancellation',
      'Battery: 7h + 23h case (30h total)',
      'Connectivity: Bluetooth 5.3, multipoint',
      'Water resistance: IPX5',
      'Charging: USB-C + Qi wireless',
    ],
    shippingInfo: 'Free express shipping. Delivered within 2–4 business days.',
    tags: ['earbuds', 'wireless', 'anc', 'audio'],
    rating: 4.6,
    reviewCount: 312,
    reviews: [],
    stock: 45,
    sku: 'APEX-EARBUDS-MAIN',
    isNew: true,
    isFeatured: false,
    status: 'active',
    createdAt: '2024-03-10',
  },
  {
    id: 'prod-7',
    slug: 'victus-gaming-laptop-17',
    name: 'HP Victus 17 Gaming Laptop',
    brand: 'HP',
    category: 'Laptops',
    categorySlug: 'laptops',
    images: ['/assets/victuslaptop.png'],
    price: 2299,
    shortDescription: 'The 17-inch powerhouse for creators and gamers who want more screen real estate.',
    description:
      'More room to create, more room to dominate. The HP Victus 17 brings the same RTX 4070 performance to a larger 17.3" QHD display at 165Hz, perfect for immersive gaming or professional content creation on a canvas worthy of your work.',
    details: [
      'Display: 17.3" QHD IPS, 165Hz',
      'Processor: Intel Core i9-13900HX',
      'GPU: NVIDIA GeForce RTX 4070 8GB',
      'RAM: 32GB DDR5 | Storage: 1TB NVMe SSD',
      'Battery: 83Wh',
    ],
    shippingInfo: 'Free express shipping. Delivered within 3–5 business days.',
    tags: ['laptop', 'gaming', 'rtx', 'intel', '17-inch'],
    rating: 4.4,
    reviewCount: 98,
    reviews: [],
    stock: 8,
    sku: 'HP-VICTUS17-MAIN',
    isNew: false,
    isFeatured: false,
    status: 'active',
    createdAt: '2024-02-20',
  },
  {
    id: 'prod-8',
    slug: 'resonance-bookshelf-speakers',
    name: 'Resonance Bookshelf Speakers',
    brand: 'Resonance Audio',
    category: 'Audio',
    categorySlug: 'audio',
    images: ['/assets/doublespeaker.png'],
    price: 899,
    shortDescription: 'Compact hi-fi speakers with a soundstage that defies their size.',
    description:
      'Do not let their size fool you. The Resonance Bookshelf Speakers deliver a full-range soundstage that competes with tower speakers twice their price. Silk dome tweeters and 6.5" long-throw woofers work in perfect harmony through a carefully tuned bass reflex port.',
    details: [
      'Tweeter: 1" silk dome',
      'Woofer: 6.5" long-throw paper cone',
      'Frequency response: 45Hz – 40kHz',
      'Sensitivity: 88dB @ 1W/1m',
      'Power handling: 100W RMS',
    ],
    shippingInfo: 'Free shipping. Delivered within 3–5 business days.',
    tags: ['speakers', 'hi-fi', 'bookshelf', 'stereo'],
    rating: 4.7,
    reviewCount: 134,
    reviews: [],
    stock: 17,
    sku: 'RESON-BOOK-MAIN',
    isNew: false,
    isFeatured: false,
    status: 'active',
    createdAt: '2023-10-01',
  },
]

// ─── Mock Orders ──────────────────────────────────────────────────────────────

export const mockOrders: Order[] = [
  {
    id: 'ord-1',
    orderNumber: '#EB-2024-00142',
    customerId: 'cust-1',
    customerName: 'Alexandra Mitchell',
    customerEmail: 'alex.mitchell@example.com',
    items: [
      { productId: 'prod-1', name: 'Samsung Galaxy S22', image: '/assets/s22.png', price: 1599, quantity: 1, sku: 'S22-BLK-256' },
    ],
    subtotal: 1599,
    shipping: 0,
    tax: 128,
    total: 1727,
    status: 'delivered',
    paymentStatus: 'paid',
    paymentMethod: 'Visa •••• 4242',
    shippingAddress: { fullName: 'Alexandra Mitchell', email: 'alex@example.com', phone: '+1 555 0101', address1: '142 Park Avenue', city: 'New York', state: 'NY', zip: '10022', country: 'United States' },
    trackingNumber: 'UPS1Z9284AB1',
    carrier: 'UPS',
    createdAt: '2024-04-01',
    updatedAt: '2024-04-05',
  },
  {
    id: 'ord-2',
    orderNumber: '#EB-2024-00141',
    customerId: 'cust-2',
    customerName: 'James Harrington',
    customerEmail: 'j.harrington@example.com',
    items: [
      { productId: 'prod-2', name: 'HP Victus Gaming Laptop', image: '/assets/victuslaptop.png', price: 1799, quantity: 1, sku: 'VICTUS-SLV-512' },
      { productId: 'prod-4', name: 'Elite Gaming Headset Pro', image: '/assets/gamingheadphone.png', price: 1799, quantity: 1, sku: 'APEX-BLK' },
    ],
    subtotal: 3598,
    shipping: 0,
    tax: 288,
    total: 3886,
    status: 'shipped',
    paymentStatus: 'paid',
    paymentMethod: 'Mastercard •••• 8871',
    shippingAddress: { fullName: 'James Harrington', email: 'j.harrington@example.com', phone: '+44 20 7946 0958', address1: '42 Mayfair Court', city: 'London', state: 'England', zip: 'W1K 1AA', country: 'United Kingdom' },
    trackingNumber: 'DHL9928374655',
    carrier: 'DHL',
    createdAt: '2024-04-03',
    updatedAt: '2024-04-04',
  },
  {
    id: 'ord-3',
    orderNumber: '#EB-2024-00140',
    customerId: 'cust-3',
    customerName: 'Sofia Blanc',
    customerEmail: 'sofia.b@example.com',
    items: [
      { productId: 'prod-3', name: 'Dual Tower Speaker System', image: '/assets/doublespeaker.png', price: 2699, quantity: 1, sku: 'RESON-BLK' },
    ],
    subtotal: 2699,
    shipping: 0,
    tax: 216,
    total: 2915,
    status: 'processing',
    paymentStatus: 'paid',
    paymentMethod: 'Apple Pay',
    shippingAddress: { fullName: 'Sofia Blanc', email: 'sofia.b@example.com', phone: '+33 1 40 00 00 00', address1: '8 Rue de Rivoli', city: 'Paris', state: 'Île-de-France', zip: '75001', country: 'France' },
    createdAt: '2024-04-05',
    updatedAt: '2024-04-05',
  },
  {
    id: 'ord-4',
    orderNumber: '#EB-2024-00139',
    customerId: 'cust-4',
    customerName: 'Kenji Watanabe',
    customerEmail: 'k.watanabe@example.com',
    items: [
      { productId: 'prod-5', name: 'Samsung Galaxy S22 Ultra', image: '/assets/s22.png', price: 2199, quantity: 1, sku: 'SAM-S22U-MAIN' },
    ],
    subtotal: 2199,
    shipping: 0,
    tax: 176,
    total: 2375,
    status: 'pending',
    paymentStatus: 'pending',
    paymentMethod: 'PayPal',
    shippingAddress: { fullName: 'Kenji Watanabe', email: 'k.watanabe@example.com', phone: '+81 3 1234 5678', address1: '3-1 Marunouchi', city: 'Tokyo', state: 'Tokyo', zip: '100-0005', country: 'Japan' },
    createdAt: '2024-04-06',
    updatedAt: '2024-04-06',
  },
  {
    id: 'ord-5',
    orderNumber: '#EB-2024-00138',
    customerId: 'cust-1',
    customerName: 'Alexandra Mitchell',
    customerEmail: 'alex.mitchell@example.com',
    items: [
      { productId: 'prod-6', name: 'Apex Wireless Earbuds Pro', image: '/assets/gamingheadphone.png', price: 449, quantity: 2, sku: 'APEX-EARBUDS-MAIN' },
    ],
    subtotal: 898,
    shipping: 0,
    tax: 72,
    total: 970,
    status: 'delivered',
    paymentStatus: 'paid',
    paymentMethod: 'Visa •••• 4242',
    shippingAddress: { fullName: 'Alexandra Mitchell', email: 'alex@example.com', phone: '+1 555 0101', address1: '142 Park Avenue', city: 'New York', state: 'NY', zip: '10022', country: 'United States' },
    createdAt: '2024-03-20',
    updatedAt: '2024-03-24',
  },
]

// ─── Mock Customers ───────────────────────────────────────────────────────────

export const mockCustomers: Customer[] = [
  { id: 'cust-1', name: 'Alexandra Mitchell', email: 'alex.mitchell@example.com', phone: '+1 555 0101', totalOrders: 2, totalSpent: 2697, averageOrderValue: 1348.50, lastOrderDate: '2024-04-01', status: 'active', joinDate: '2023-08-14', lastLogin: '2024-04-06' },
  { id: 'cust-2', name: 'James Harrington', email: 'j.harrington@example.com', phone: '+44 20 7946 0958', totalOrders: 1, totalSpent: 3886, averageOrderValue: 3886, lastOrderDate: '2024-04-03', status: 'active', joinDate: '2024-01-22', lastLogin: '2024-04-03' },
  { id: 'cust-3', name: 'Sofia Blanc', email: 'sofia.b@example.com', phone: '+33 1 40 00 00 00', totalOrders: 1, totalSpent: 2915, averageOrderValue: 2915, lastOrderDate: '2024-04-05', status: 'active', joinDate: '2024-03-01', lastLogin: '2024-04-05' },
  { id: 'cust-4', name: 'Kenji Watanabe', email: 'k.watanabe@example.com', phone: '+81 3 1234 5678', totalOrders: 1, totalSpent: 2375, averageOrderValue: 2375, lastOrderDate: '2024-04-06', status: 'active', joinDate: '2024-04-06', lastLogin: '2024-04-06' },
  { id: 'cust-5', name: 'Priya Sharma', email: 'priya.s@example.com', phone: '+91 98 7654 3210', totalOrders: 3, totalSpent: 5420, averageOrderValue: 1806.67, lastOrderDate: '2024-03-28', status: 'active', joinDate: '2023-06-10', lastLogin: '2024-04-01' },
  { id: 'cust-6', name: 'Luca Ferrari', email: 'luca.f@example.com', phone: '+39 02 1234 5678', totalOrders: 0, totalSpent: 0, averageOrderValue: 0, status: 'active', joinDate: '2024-04-04', lastLogin: '2024-04-04' },
]

// ─── Mock Coupons ─────────────────────────────────────────────────────────────

export const mockCoupons: Coupon[] = [
  { id: 'cpn-1', code: 'LUXURY10', type: 'percentage', value: 10, usageLimit: 500, usageCount: 142, status: 'active', createdAt: '2024-01-01' },
  { id: 'cpn-2', code: 'WELCOME20', type: 'percentage', value: 20, minOrderValue: 500, usageLimit: 1000, usageCount: 310, status: 'active', createdAt: '2024-01-01' },
  { id: 'cpn-3', code: 'VIP15', type: 'percentage', value: 15, usageLimit: 100, usageCount: 100, status: 'expired', expiryDate: '2024-03-31', createdAt: '2024-01-15' },
  { id: 'cpn-4', code: 'FREESHIP', type: 'free_shipping', value: 0, minOrderValue: 200, usageLimit: 200, usageCount: 78, status: 'active', createdAt: '2024-02-01' },
]

// ─── Mock Analytics ───────────────────────────────────────────────────────────

export const mockRevenueData: RevenueDataPoint[] = [
  { date: 'Apr 1', revenue: 8420, orders: 5 },
  { date: 'Apr 2', revenue: 12350, orders: 7 },
  { date: 'Apr 3', revenue: 9800, orders: 6 },
  { date: 'Apr 4', revenue: 15200, orders: 9 },
  { date: 'Apr 5', revenue: 11400, orders: 8 },
  { date: 'Apr 6', revenue: 18750, orders: 12 },
  { date: 'Apr 7', revenue: 14300, orders: 10 },
  { date: 'Apr 8', revenue: 9200, orders: 6 },
  { date: 'Apr 9', revenue: 13100, orders: 9 },
  { date: 'Apr 10', revenue: 16800, orders: 11 },
  { date: 'Apr 11', revenue: 21200, orders: 14 },
  { date: 'Apr 12', revenue: 17400, orders: 12 },
  { date: 'Apr 13', revenue: 19600, orders: 13 },
  { date: 'Apr 14', revenue: 22100, orders: 15 },
]

export const mockTopProducts: TopProduct[] = [
  { id: 'prod-1', name: 'Samsung Galaxy S22', revenue: 47970, units: 30, image: '/assets/s22.png' },
  { id: 'prod-2', name: 'HP Victus Gaming Laptop', revenue: 34181, units: 19, image: '/assets/victuslaptop.png' },
  { id: 'prod-4', name: 'Elite Gaming Headset Pro', revenue: 30583, units: 17, image: '/assets/gamingheadphone.png' },
  { id: 'prod-3', name: 'Dual Tower Speaker System', revenue: 26990, units: 10, image: '/assets/doublespeaker.png' },
  { id: 'prod-5', name: 'Samsung Galaxy S22 Ultra', revenue: 48378, units: 22, image: '/assets/s22.png' },
]

export const mockOrdersStatusData = [
  { name: 'Delivered', value: 42, color: '#2ECC71' },
  { name: 'Shipped',   value: 18, color: '#C9A84C' },
  { name: 'Processing',value: 24, color: '#3B82F6' },
  { name: 'Pending',   value: 10, color: '#9A9A90' },
  { name: 'Cancelled', value: 6,  color: '#E74C3C' },
]

export const mockTrafficData = [
  { name: 'Organic Search', value: 38, color: '#C9A84C' },
  { name: 'Direct',         value: 25, color: '#D4B870' },
  { name: 'Social',         value: 20, color: '#A08030' },
  { name: 'Email',          value: 12, color: '#9A9A90' },
  { name: 'Paid',           value: 5,  color: '#6B6B60' },
]
